/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import exceptionsML.InputsVaciosException;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JOptionPane;
import matrizletras.matrixManager;
import objectsML.letras;

/**
 *
 * @author angel
 */
public class principalFrame extends javax.swing.JFrame {

    Color baseColor;
    Color letterColor;
    matrixManager matrixM;
    letras letterC = new letras();

    public principalFrame(Color baseColor, Color letterColor) throws InputsVaciosException {
        initComponents();
        this.baseColor = baseColor;
        this.letterColor = letterColor;
        matrixM = new matrixManager(baseColor, letterColor);
        setPixel(matrixPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entryTextField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        matrixPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Letras");

        jLabel1.setText("Ingrese la Letra:");

        viewButton.setText("Visualizar");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout matrixPanelLayout = new javax.swing.GroupLayout(matrixPanel);
        matrixPanel.setLayout(matrixPanelLayout);
        matrixPanelLayout.setHorizontalGroup(
            matrixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        matrixPanelLayout.setVerticalGroup(
            matrixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matrixPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(entryTextField)
                        .addGap(18, 18, 18)
                        .addComponent(viewButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton))
                .addGap(18, 18, 18)
                .addComponent(matrixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        try {
            matrixM.setLetterAndColor(entryTextField.getText().replaceAll(" ", "").replaceAll("\t", "").replaceAll("\n", ""));
        } catch (InputsVaciosException e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void setPixel(Container panel) {
        Dimension panelDimension = new Dimension(letterC.matrixSize * letterC.PixelSize, letterC.matrixSize * letterC.PixelSize);
        panel.setSize(panelDimension);
        panel.setPreferredSize(panelDimension);
        panel.setMaximumSize(panelDimension);

        Insets insets = panel.getInsets();
        for (int y = 0; y < letterC.matrixSize; y++) {
            for (int x = 0; x < letterC.matrixSize; x++) {
                panel.add(matrixM.getButtonList().get(y).get(x).getBoton());
                matrixM.getButtonList().get(y).get(x).getBoton().setBounds(x * letterC.PixelSize + insets.left, y * letterC.PixelSize + insets.top, letterC.PixelSize, letterC.PixelSize);
            }
        }
        System.out.println("Matriz agregada");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entryTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel matrixPanel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
